---
title: "In-class Exercise 4"
author: "Alicia"
date: "6 May 2023"
date-modified: "`r Sys.Date()`"
editor: visual

execute:
  echo: true
  eval: true
  warning: false
---

# Getting Started

## Installing and launching R packages

```{r}
pacman::p_load(rstatix, gt, patchwork, tidyverse, webshot2, png)
```

## Importing the data

```{r}
exam_data <- read_csv("data/Exam_data.csv")
```

## Visualizing normal distribution

::: panel-tabset
## The plot

```{r}
#| echo: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()
```

## The code chunk

```{r}
#| eval: false
#| fig-width: 4
#| fig-height: 4
ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()
```
:::

::: callout-note
We can see that the points deviate significantly from the straight diagonal line. This is a clear indication that the set of data is not normally distributed.
:::

::: panel-tabset
## The plot

```{r}
#| echo: false
qq <- ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()

sw_t <- exam_data %>%
  shapiro_test(ENGLISH) %>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp)
table_png <- png::readPNG(tmp,
                          native = TRUE)

qq + table_png
```

## The code chunk

```{r}
#| eval: false
qq <- ggplot(exam_data,
       aes(sample=ENGLISH)) +
  stat_qq() +
  stat_qq_line()

sw_t <- exam_data %>%
  shapiro_test(ENGLISH) %>%
  gt()

tmp <- tempfile(fileext = '.png')
gtsave(sw_t, tmp)
table_png <- png::readPNG(tmp,
                          native = TRUE)

qq + table_png
```
:::
